version: 2

registries:
  corti-github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_TOKEN }}

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    open-pull-requests-limit: 1
    registries: "*"  # Use all, i.e. the ecosystem default and corti-github, registries
    directory: "/"
    labels:
      - "dependabot"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"  # Allow both direct and indirect updates for all packages
    commit-message:
      prefix: "pip prod"
      prefix-development: "pip dev"
      include: "scope"
    # https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#insecure-external-code-execution
    insecure-external-code-execution: allow
