fail_fast: False
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files  # Check for large files.
    -   id: check-ast  # Check Python file syntax using the ast module.
    -   id: check-json  # Check JSON file syntax.
    -   id: check-merge-conflict  # Check for merge conflict strings.
    -   id: check-toml  # Check TOML file syntax.
    -   id: check-xml  # Check XML file syntax.
    -   id: check-yaml  # Check YAML file syntax.
    -   id: detect-private-key  # Check for private keys.
    -   id: end-of-file-fixer  # Ensure files end with a newline.
    -   id: trailing-whitespace  # Check for trailing whitespace.
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-format
      - id: ruff-check
-   repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
    -   id: yesqa  # Check if there are any unnecessary 'noqa' comments in the code.
-   repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
    -   id: poetry-check  # Validate the pyproject.toml file.
    -   id: poetry-lock  # Lock dependencies on changes to the pyproject.toml.
    -   id: poetry-install  # Install dependencies from the lock file on checkout and merge.
